package person;
import enums.Building;
import enums.FacultyType;
import enums.PersonStatus;

/**
 * <p>The <strong>Faculty</strong> class holds information about a faculty member.</p>
 * <ul>
 * <li><strong>first name:</strong> first name of the faculty</li>
 * <li><strong>last name:</strong> last name of the faculty</li>
 * <li><strong>suid:</strong> SeattleU identification number</li>
 * <li><strong>status:</strong> the status of the faculty (see PersonStatus enum)</li>
 * <li><strong>faculty type:</strong> the type of faculty (see FacultyType enum)</li>
 * <li><strong>office:</strong> includes building (i.e. ENGR) and room number (i.e 504)</li>
 * <li><strong>email:</strong> the school (i.e. SU) email address</li>
 * </ul>
 * <p>For example, faculty <strong>Sheila Oh</strong></p>
 * <ul>
 * <li><strong>first name:</strong> Sheila</li>
 * <li><strong>last name:</strong> Oh</li>
 * <li><strong>suid:</strong> 100013</li>
 * <li><strong>status:</strong> ACTIVE</li>
 * <li><strong>faculty type:</strong> SEN_INSTRUCT</li>
 * <li><strong>office (building/room):</strong> ENGR 504</li>
 * <li><strong>email:</strong> ohsh@seattleu.edu</li>
 * </ul>
 * 
 * @Jun Liao
 */
public class Faculty extends Person{
    // TODO: add Faculty fields

    private FacultyType type;             // - faculty type (see FacultyType)
    private String office;                // - office (see Building)
    private String phoneNum;              // - phone
    private static int uniqueID = 100001; // starts from 100001, increment every time after a Faculty type object was created


    /**
     * The class's constructor
     * @param firstName
     * @param lastName
     * @param type FacultyType
     * @param bldg Building name (see Building)
     * @param room The faculty's room number
     * @param email The faculty's email address
     */
    public Faculty(String firstName, String lastName, FacultyType type, Building bldg,  int room, String email) {
        // TODO: implement Faculty constructor
        this(firstName, lastName);
        this.type = type;
        this.office = bldg + " " + room;
        super.setEmail(email);      // set email because it's input from outside (Not auto-generated by system)
    }
    /**
     *
     * @param firstName   The first name of the faculty
     * @param lastName    The last name of the faculty
     */
    public Faculty(String firstName, String lastName) {
        // TODO: implement Faculty constructor
        super(firstName, lastName, uniqueID);     // uniqueID passed into "super(firstName, lastName, uniqueID)" to set SUID
        // "uniqueID" starts from 100001,
        // auto increments every time after a Faculty instance was created,
        uniqueID ++;
    }



    /**
     * According to homework required format,
     * lists information in the Faculty,
     * and converts it to a string.
     * @return A string representing Faculty object
     */
    @Override
    public String toString(){
        return "Faculty" +
                ": Name=" + super.getName() +
                ", SUID=" + super.getSUID() +
                ", Email=" + super.getEmail() +
                ", Status=" + super.getStatus() +
                ", Type=" + type +
                ", Office=" + office
        ;
    }

    public String getName(){
        return super.getName();
    }


}
