package person;
import enums.PersonStatus;

/**
 * The Person class is used to be inherited by Faculty and Student class
 * since in fact everybody is-a person, they share common fileds like
 * firstName, lastName, status, email, SUID…
 *
 * @author Jun Liao
 */

public abstract class Person {
    // Person fields
    private String fistName;              // - first name
    private String lastName;              // - last name
    private PersonStatus status;          // - status (see PersonStatus)
    String email;                         // - email (generated by system, also can be re-set from outside through "setEmail" method)
    private int SUID;                     // - SUID

    /**
     * Constructor
     * @param firstName Person's first name
     * @param lastName Person's last name
     * @param uniqueID SUID
     */
    protected Person(String firstName, String lastName, int uniqueID) {
        this(firstName, lastName);
        this.SUID = uniqueID;
    }
    private Person(String firstName, String lastName) {
        this.fistName = firstName;
        this.lastName = lastName;
        // If a Person can be initialized successfully, status is auto-set as "ACTIVE"
        this.status = PersonStatus.ACTIVE;
        // Email would be auto-generated by Person's name (but it also can be re-set)
        this.email = autoGenerateEmail(firstName, lastName);
    }

    /**
     * Auto generates the email address for a student with his/her name
     * @param firstName
     * @param lastName
     * @return The student's email the system auto generates for his/her
     */
    private String autoGenerateEmail(String firstName, String lastName) {
        return firstName.toLowerCase() + lastName.toLowerCase() + "@seattleu.edu";
    }

    protected void setEmail(String email) {
        this.email = email;
    }

    protected int getSUID() {
        return SUID;
    }

    protected String getName() {
        return fistName + " " + lastName;
    }

    protected PersonStatus getStatus() {
        return status;
    }

    protected String getEmail() {
        return email;
    }
}
